### PR TITLE
Update PubSubStandard_singleNode.yml

### PR DESCRIPTION
**Pull request by tfary1832**
Update the SMF host port to 55566 to fix the issue with macOS as proposed in JIRA issue DOC-907.

### CODE REVIEW

**Comment by Mrc0113** [comment]
@tfary1832 any reason port `55566` was chosen? I would like to make sure we are consistent with ports in other resources as well and was potentially thinking about 4 5s `5555` or 4 4s `4444` for the port instead. 

@tamimigithub - FYI

**Comment by tfary1832** [comment]
No specific reason. I read someone on the community site fixed the issue using 55566 so thought it was a good place to start. 

Feel free to change it to something better.

**Comment by Mrc0113** [comment]
@tfary1832 note that SOL-51814 has been opened and this PR should be put on hold until that research is completed.

**Comment by Mrc0113** [comment]
Closed - no longer applies. Port is set to `55554`

**Pull request closed without merging**
